### PR TITLE
removed updation of style while text updates

### PR DESCRIPTION
**Pull request by thesujai**
## Description

This change will not allow the input fields(Which has preprocessed input) of any page to appear focused when navigated with keyboard.
I have described the problem in this[ comment](https://github.com/learningequality/kolibri/issues/9077#issuecomment-1717541887)

#### Issue addressed

Fixes: #[9077](https://github.com/learningequality/kolibri/issues/9077)

### Before/after screenshots

Before
[Screencast from 15-09-23 04:49:34 PM IST.webm](https://github.com/learningequality/kolibri-design-system/assets/120925871/7322c415-d412-4846-bc9b-cd6e8b3a1074)

After:

[Screencast from 15-09-23 04:46:38 PM IST.webm](https://github.com/learningequality/kolibri-design-system/assets/120925871/6c01cdf6-651a-442b-96a9-fa23c6167c22)

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical and brittle code paths are covered by unit tests
- [ ] The change has been added to the `changelog`

## Reviewer guidance

- [ ] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?
- [ ] _Add other things to check for here_

### CODE REVIEW

**Comment by MisRob** [comment]
Hi @thesujai, thanks for the contribution! I tested it a bit and looking at your comment here https://github.com/learningequality/kolibri/issues/9077#issuecomment-1717541887 and the code change, it makes much sense to me. I think your understanding of the problem is great. Thanks for debugging it thoroughly.

Looking at the history of `KTextBox` I can see that the line in the watcher your removed was in this component since the very beginning. `KTextBox` went through many other updates since then in regards to focus outline, so it is quite possible we can remove this safely. I think we will need to indeed do this change to fix the issue, but let me connect with our QA team next week to test for regressions in Kolibri just to be confident that it won't break anything else. It might take several days as we have quite full QA queue. I'll be in touch.

**Comment by MisRob** [comment]
@thesujai Congratulations and thank you!

Our QA team just confirmed all is good. I will do a few last touches here in regards to our changelog and then merge.

**Comment by MisRob** [comment]
@rtibbles I sneaked in renaming the changelog check action (https://github.com/learningequality/kolibri-design-system/pull/451) from `check` to `check-changelog` here because on this PR I noticed that `check` was shown in the settings of required checks which doesn't really say much. @thesujai apologies for my mess.

**Review by MisRob — APPROVED** [review]
Great work @thesujai

**Comment by thesujai** [comment]
@MisRob Thank you!
I found this community active and helpful, I will look forward to contributing more.
If there are any good first issue with inactive assignee(As all are assigned) or a relatively simple issue please let me know.
Thank You:)

**Comment by MisRob** [comment]
Thanks @thesujai, I'm glad to hear that.

We're constantly adding new issues that are open for contribution so you're welcome to check [Kolibri good first issues](https://github.com/learningequality/kolibri/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+no%3Aassignee), [Kolibri Design System ones](https://github.com/learningequality/kolibri-design-system/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+no%3Aassignee+), as well as [Studio ones](https://github.com/learningequality/studio/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22).

Just in case we run out of them again, and you'd like to work on something, contact us in GitHub Discussions of one of those projects. We have plenty of work, just sometimes not managing to open issues in time :) I just fed some more into Kolibri backlog.

**Pull request merged**
