### PR TITLE
Add purple clickable icons for KRouterLink

### PR DESCRIPTION
**Pull request by sairina**
## Summary
Updated `KIcon` in `KRouterLink` so that `KRouterLink` now has `icon` and `iconAfter` props.

### Addresses
Issue #135 

### Screenshots After
Examples of icon placement for `icon` and `iconAfter` props:
|For LTR|For RTL|
|--|--|
|Screen Shot 2021-02-08 at 9 22 11 PM|Screen Shot 2021-02-08 at 9 37 50 PM|

### Screenshots Before
Screen Shot 2021-02-03 at 10 03 33 PM

### CODE REVIEW

**Comment by indirectlylit** [comment]
https://github.com/learningequality/kolibri-design-system/issues/103 seems related?

**Comment by sairina** [comment]
Hmm, I'm not sure if this is related to this particular PR because I didn't work on any code around `KButton` for this, but I know this is one of the components that were mentioned that should all have similar behavior, so I'd be happy to take a look at this issue after this one is closed out! 

Speaking of which, @indirectlylit , can you take a look at the updated `KRouterLink` code (specifically for the icon) - I made sure to fix the slot issue that had brought up the `1px red border`. It turns out that because all of those `icon` slotting issues were taken care of from `KLabeledIcon`, there was no need to add a computed class to this component.

|Before|After|
|--|--|
|Screen Shot 2021-02-10 at 2 34 29 PM|Screen Shot 2021-02-10 at 2 32 05 PM|

**Comment by indirectlylit** [comment]
In chromium and firefox on mac I see this:

image

for:

```vue
        <KRouterLink
          text="router link (empty)"
          :to="{}"
          icon="facility"
          iconAfter="facility"
        />
```

**Review by indirectlylit — APPROVED** [review]
merging in so we can see everything together. Will file follow-up for cross-component consistency

**Pull request merged**
