### PR TITLE
Adding title attribute in  K-Breadcrumbs

### PR DESCRIPTION
**Pull request by RONAK-AI647**
## Description
It adds title attribute in KBreadcrumbs component which enable us read the truncated texts anywhere in KBreadcrumbs.
#### Issue addressed
#208 
Addresses #*PR# HERE*

### **Before**

image

**After screenshots**

image

## Changelog

  - **Description:** Adding title attribute in Kbreadcrumbs.
  - **Products impact:** updated API
  - **Addresses:** kolibri-design-system/issue 208
  - **Components:** KBreadcrumbs
  - **Breaking:**  no
  - **Impacts a11y:** yes 
  - **Guidance:** The truncated texts can be seen now.

## Steps to test

1. Add title attribute in breadcrumbs-visible-items
2. Add title attribute in breadcrumbs-dropdown-wrapper
3. ...

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical and brittle code paths are covered by unit tests
- [ ] The change is described in the changelog section above

## Reviewer guidance

- [ ] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?
- [ ] _Add other things to check for here_

## Comments
Now the truncated texts which were not visible completely , can be seen easily .

### CODE REVIEW

**Comment by MisRob** [comment]
Thank you @RONAK-AI647! I will wait for @radinamatic's confirmation of the expected behavior we discussed in https://github.com/learningequality/kolibri-design-system/issues/208#issuecomment-2487678892.

@radinamatic you can also preview @RONAK-AI647's update here https://deploy-preview-839--kolibri-design-system.netlify.app/kbreadcrumbs/

**Comment by radinamatic** [comment]
@RONAK-AI647 thank you for your contribution! 👏🏽 

Useful addition from the usability point of view, although since the `title` attribute is most often ignored by screen readers, this change does not have major impact on accessibility or keyboard navigation, but will support sighted users in general 🙂

**Review by radinamatic — APPROVED** [review]
LGTM! 💯 :shipit: 🚀

**Comment by RONAK-AI647** [comment]
Thank You @radinamatic for review .It will be great if @MisRob approves if everything is fine and push .

**Comment by MisRob** [comment]
Good to hear all looks well. I will finish review, @RONAK-AI647.

**Comment by MisRob** [comment]
Side note @radinamatic, I think screen readers may be fine, because it's just css text truncation - the whole text is present in markup

**Comment by radinamatic** [comment]
Yes @MisRob, that was evident during the testing 👍🏽 🙂

**Comment by MisRob** [comment]
It looks good to me @RONAK-AI647, thanks! Would you rebase your branch on top of the latest `develop` branch and resolve conflicts so we can merge? We recently updated the Node version to v18 and vue to v2.7. So after rebasing, you'd need to switch your Node version and run `yarn install`. Then run `yarn lint-fix`.

**Comment by RONAK-AI647** [comment]
@MisRob It does not work , why these checks failing I don't understand, do i open a new pr ??

**Comment by RONAK-AI647** [comment]
@MisRob I have opened a new PR because this PR after rebasing had conflicts .Take a look there and if everything is right , close them both alongwith.

**Comment by MisRob** [comment]
Closing in favor of https://github.com/learningequality/kolibri-design-system/pull/872. Thanks @radinamatic and @RONAK-AI647.

**Pull request closed without merging**
