### PR TITLE
Updated KTable Documentation

### PR DESCRIPTION
**Pull request by BabyElias**
## Description
Updated KTable documentation to include more examples for custom column widths and use of slots.

## Changelog

  - **Description:** Updated documentation for KTable
  - **Products impact:** None
  - **Addresses:**
  - **Components:** KTable
  - **Breaking:** No
  - **Impacts a11y:** No
  - **Guidance:** 

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical and brittle code paths are covered by unit tests
- [ ] The change is described in the changelog section above

## Reviewer guidance

- [ ] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?
- [ ] _Add other things to check for here_

### CODE REVIEW

**Review by marcellamaki — APPROVED** [review]
This looks great @BabyElias! The examples are clear and the explanation is concise but detailed enough to outline the different use cases. Nice work. I think the changelog needs to be updated before merge, but otherwise this looks good to me

**Comment by BabyElias** [comment]
Updated Changelog @marcellamaki

**Comment by BabyElias** [comment]
Hey @marcellamaki , All good with the PR?

**Comment by marcellamaki** [comment]
yes! thank you @BabyElias!

**Pull request merged**
