### PR TITLE
move material icons from normal to dev dependency and update readme

### PR DESCRIPTION
**Pull request by indirectlylit**
This should make KDS 30 MB smaller for users, e.g. Kolibri, Studio, KDP

ref: https://learningequality.slack.com/archives/CTG8XDTCL/p1607447862001200

cc @nucleogenesis @jonboiser

### CODE REVIEW

**Comment by indirectlylit** [comment]
Actually, some of the other dependencies also look like dev. For example:

* `svgo`
* `@mdi/svg`?
* `@babel/core` and `@babel/preset-env`?
* also, where do we use `fuzzysearch`?

**Comment by nucleogenesis** [comment]
`fuzzysearch` is used by Keen's UIAutocomplete component.

The others ought to be good added to `devDependencies` though.

**Comment by indirectlylit** [comment]
thanks @nucleogenesis - moved those dependencies also.

Ready for review & merge

**Review by nucleogenesis — APPROVED** [review]
Thanks @indirectlylit !

**Pull request merged**
