### PR TITLE
Add focus outline to password type inputs when navigating using keyboard

### PR DESCRIPTION
**Pull request by andersan**
## Description

Focus inputs of type "password" when navigating using the keyboard.

#### Issue addressed

Fixes issue #9563 from Kolibri repo - "Missing focus ring around password inputs".

### Before/after screenshots

Before:
Screenshot from 2022-09-21 07-44-31

After:
Screenshot from 2022-09-21 07-44-06

## Steps to test

1. Link this updated Kolibri-design-system to the Kolibri repo
2. Start a devserver for the Lolibri repo
3. Create a new account in Kolibri
4. Tab through the inputs using the keyboard and note that an outline is applied to the password inputs

### At a high level, how did you implement this?
Added a new type of input (password) to the list of keyboard modality default elements.

### Does this introduce any tech-debt items?
No

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical and brittle code paths are covered by unit tests
- [x] The change has been added to the `changelog`

## Reviewer guidance

- [ ] Are there tests for this change? (not sure if this applies)
- [ ] Are all UI components LTR and RTL compliant (if applicable)?

## Post-merge updates and tracking

- [ ] Learning Platform update PR is submitted
- [ ] Learning Platform update PR is merged
- [ ] Studio update PR is submitted
- [ ] Studio update PR is merged
- [ ] Data Portal update PR is submitted
- [ ] Data Portal update PR is merged

## Comments

Unsure how to handle the post-merge updates

### CODE REVIEW

**Comment by MisRob** [comment]
Thank you @andersan, that's great.

I think we'll want to retarget this to `release-v1.4.x` (and also move the changelog item you added under the version 1.4.x section) so that we can have this update in the next patch Kolibri release (rather than waiting for the new major Kolibri 0.16 release).

Doing it via GH UI won't work in this case. If you're fine with me pushing it into your branch, I can do it. Of course, you could do it too if you'd like. Let me know what would work for you.

**Comment by MisRob** [comment]
Apologies for not mentioning it sooner, I didn't realize it in time

**Comment by andersan** [comment]
@MisRob of course please push in to the fork I made if necessary

**Comment by MisRob** [comment]
> Unsure how to handle the post-merge updates

@andersan You don't need to do anything, thank you for your diligence in filling out the PR template

**Comment by MisRob** [comment]
@andersan Alright, pushed and retargeted (after we merge this, you may need to delete your `develop` branch and check it out again since you worked directly from it so I needed to push there which will make it pretty messy if you ever work from it again).

**Comment by lauradanforth** [comment]
Thank you @andersan !! Your contribution is much appreciated in improving Kolibri for teachers and learners.

**Review by marcellamaki — APPROVED** [review]
Looks good to me. Nice work @andersan! Thanks so much for your contribution to Kolibri and the design system :)

**Pull request merged**
