### PR TITLE
KButton, KRouterLink, KExternalLink Styling

### PR DESCRIPTION
**Pull request by sairina**
## Description

Fixes the inconsistent styling, props, etc. in the aforementioned components.

#### Issue Addressed

Addresses #166 
Note: I was unable to reproduce the issue with the underline appearing next to the icon seen here:
image

### Before/After Screenshots

Browser: Chrome

Browser: Firefox

Browser: Safari

Browser: Opera

## Steps to Test

Paste the following code into a test page: 
```vue
<KExternalLink
  text="external (google)"
  href="https://google.com"
  icon="facility"
  iconAfter="facility"
/>
<br>
<KRouterLink
  text="router link (empty)"
  :to="{}"
  icon="facility"
  iconAfter="facility"
/>
<br>
<KButton
  text="button (alert)"
  appearance="basic-link"
  icon="facility"
  iconAfter="facility"
  @click="console.log('hello')"
/>
```

## (Optional) Implementation Notes

Matched the slots with `KButton` as noted in the original issue, and added hovering to make sure icons also changed color.

### Does this introduce any tech-debt items?

- Timing of the hover transition for the link has not yet been addressed.
- I removed `KLabeledIcon` in `KRouterLink` - will that have a side effect?

## Checklist for the Reviewer

- [ ] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?

### CODE REVIEW

**Comment by nucleogenesis** [comment]
I checked this out quickly and found that the KRouterLink isn't swapping the icon and iconAfter in RTL.

Otherwise this looks great!

screenshot-localhost_8000-2021 03 03-14_14_13

screenshot-localhost_8000-2021 03 03-14_14_50

**Comment by sairina** [comment]
@nucleogenesis That is so weird! I'm trying to reproduce it on my computer. What browser are you using?

**Comment by sairina** [comment]
@indirectlylit I'm also running Firefox (v86.0) on mac, and I can't seem to reproduce either the whitespace or @nucleogenesis 's issue with the RTL for `iconAfter` 😩  . Are you able to recreate the RTL one?

|Arabic|English|
|--|--|
|Screen Shot 2021-03-09 at 8 09 50 PM|Screen Shot 2021-03-09 at 8 10 25 PM|

**Comment by sairina** [comment]
@radinamatic If you have time, would you be able to link this branch from this PR in KDS to Kolibri to test this? I've tried the following browsers (both using BrowserStack and on my own computer) to reproduce the two issues shared above:

1. When switching for RTL language, the `KRouterLink` flips the icon
screenshot-localhost_8000-2021 03 03-14_14_50
2. The underline next to the icons
image

I've been trying to unsuccessfully reproduce these two issues in the following browsers since the issues were reported:
- FIrefox 86 in Windows 10
- Safari 14 on Mac OS Catalina
- Chrome 89 on Mac OS Catalina
- Edge 89 on Mac OS Big Sur

**Comment by marcellamaki** [comment]
Manual QA of the issues in the most recent comment/update worked for me on Chrome, Firefox, and Safari! Would appreciate one more quick look over of the code from @nucleogenesis or @indirectlylit to make sure there's nothing KDS-implementation-specific/breaking change that I'm missing as I'm still getting up to speed on all of the KComponents. Thanks! 😊

**Review by indirectlylit — APPROVED** [review]
I haven't tested, but I don't see any red flags in the code

**Comment by indirectlylit** [comment]
looks like there is one merge conflict that will need to be resolved

**Pull request merged**
