### PR TITLE
Remove hardcoded fill color within icon svg files

### PR DESCRIPTION
**Pull request by LianaHarris360**
## Description

Co-authored with @nucleogenesis 
This pr addresses the issue where some `KIcon` colors not being overridden. Instances where the icon SVG files contained `fill="black"` were removed so that the `:color` property could work.
 
#### Issue addressed

Addresses #395 

### Before/after screenshots
For example, with the color property set to pink:
```
      <KIcon
        v-if="aliasList && aliasList.length"
        :icon="aliasList[0]"
        color="pink"
        class="icon"
      />
```
The icon color is overridden as expected:
Screenshot 2023-08-22 at 1 04 50 PM

### At a high level, how did you implement this?

Removed hardcoded fill color within some SVG files

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical and brittle code paths are covered by unit tests
- [ ] The change has been added to the `changelog`

## Reviewer guidance

- [ ] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?
- [ ] _Add other things to check for here_

## Comments
Selecting the Netlify preview link and navigating to the Icon page will show the display of icons with the color overridden.

### CODE REVIEW

**Comment by LianaHarris360** [comment]
@tomiwaoLE @jtamiace @marcellamaki 
Are there some cases where the color should not be overridden? Such as with the a11y icon and the Learning activities icons:
Screenshot 2023-08-22 at 1 20 56 PM

Screenshot 2023-08-22 at 1 04 35 PM

**Comment by MisRob** [comment]
> Are there some cases where the color should not be overridden?

If this shows to be indeed the case, I'd suggest mentioning it in the documentation at relevant places, one of them being `KIcon`'s `color` prop documentation, so that developers know it's not intended work in some cases

**Comment by LianaHarris360** [comment]
`Note:` This PR is currently a draft only to demonstrate that setting the`:color` prop to pink correctly displays the icons to be pink. Decisions regarding the icons that do not change color with the `:color` property need to be made to determine if that is the intended presentation. If all color changes are confirmed to be correct, the line `:color="pink"` will be removed from the `KIcon` documentation page, otherwise appropriate changes will be made. Other than that, this PR is ready for review.

**Comment by indirectlylit** [comment]
Hi folks! I'm still lurking around in KDS :)

>  icons that do not change color

One option would be to add a new boolean property like `fixedColor: true` to these icon definitions:

https://github.com/learningequality/kolibri-design-system/blob/8e5916b9f56324f18814c3510e141d1772114797/lib/KIcon/iconDefinitions.js#L13-L17

When `fixedColor: true`, trying to use the `color` prop of `KIcon` would show an error, helping prevent inadvertent color overrides.

Just an idea!

**Comment by LianaHarris360** [comment]
Hi @indirectlylit, thank you for lurking around in KDS,  I like this suggestion! Displaying an error in the console/logs when the color prop is used on icons where the `fixedColor` is `true` would be a great way to inform developers of icons with unchanging colors in addition to referencing it in the documentation.

**Comment by LianaHarris360** [comment]
This PR has been updated to reflect agreed upon changes such as:

- `fixedColor` property that determines if the icon color is customizable or not has been added to `lib/KIcon/iconDefinitions.js`
- Icons where the property `fixedColor` is `true` will provide an error if the `KIcon` color property is set. 
    - For example with the icon `a11y`:
Screenshot 2023-09-05 at 1 24 34 PM


`Note:` A follow-up issue will be created for icons that use multiple colors but should still be customizable.

**Review by marcellamaki — APPROVED** [review]
This looks great @LianaHarris360 and @nucleogenesis . As we discussed during KDS, there will probably be some follow up work around our icons after this, but this is an awesome start and a really helpful fix. Thank you 🎉

**Pull request merged**
