### PR TITLE
Add copyToClipboard, home, (un)publishedResource icons, generate RST replacements

### LINKED ISSUE #141: Studio icons missing in KDS for the substitutions in docs
I was not able to find [docs-substitutions](https://kolibri-design-system.netlify.app/icons/#rst) for these Studio icons:

Icon | (proposed) Name | Location
------- | ------- | -
copy-channel-token  | `copyBorder` | copy-channel-token-location
kolibri-violet-info | _possibly just missing the **colored** style_ | kolibri-violet-info-location
home | `home` | home-location
unpublishedResource | `unpublishedResource` | unpublished-location
unpublishedChanges | `unpublishedChange` | :arrow_up: 

cc @nucleogenesis @indirectlylit

### PR DESCRIPTION
**Pull request by nucleogenesis**
## Description

Currently, there is no `copy` icon with the `Outline` style in KDS - which is necessary in Studio.

In Studio, however, we have not fully applied `KIcon` and `KIconButton` and so forth - so there are many icons used there by way of Vuetify's handling of material icons.

But - @radinamatic needs these icons on hand so she can update documentation with access to all of the icons we see in our products, even if the product isn't currently getting the icon from KDS.

Thus I've added it here.

#### Issue addressed

Fixes #141 

Also - the `unpublishedChanges` and `publishedResource` icons are `tokens.success`.

Initially, the closest color we had was `brand.secondary` which is also `tokens.focusOutline` - this matched the similar version from Vuetify currently used in Studio.

That did not pass muster as an icon for a11y purposes - so I've opted to use that darker green `tokens.success` color which passes in the icon context:

changes-publish-icon-color-contrast-using-success

## Steps to test

1. Go to the deployed Netlify testing site at the bottom here in the "Github Actions" section.
2. Go to icons
3. Type in "copy" to see the two copy icons.
4. Scroll to the bottom for the RST Replacement text - see that the `copyToClipboard` icon is there and is acceptable.

@jtamiace - do you agree that `copyToClipboard` is a solid alias for that icon? It matches the actual use of it in Studio anyway. See @indirectlylit 's comment from #141 

screenshot-github com-2021 04 09-16_23_29

---

@radinamatic does this solve the concerns you had in #141?

### CODE REVIEW

**Comment by radinamatic** [comment]
@nucleogenesis this resolves the outlined `copy` icon, but not the rest of the missing Studio icons I reported in the https://github.com/learningequality/kolibri-design-system/issues/141

LEDev2104 (start)  Running  - Oracle VM VirtualBox_044

If that is what is addressed with this PR, I'm happy to approve 🙁

**Comment by radinamatic** [comment]
All icons are finally in! 💯 

What I don't see are the required colors, primary for the `info` and secondary for the `Resource` when I build the docs atm, but I see that all have the [`defaultColor` property in the `iconDefinitions.js`](https://github.com/nucleogenesis/kolibri-design-system-1/blob/82aa269008f328eb912ab566c536227bf0f57de4/lib/KIcon/iconDefinitions.js#L152). 

Selection_047

If that is all going to fall in place once this PR is merged, then all's good!

One last thing that might need a retouch are the _aliases_. Technically, in Studio UI both `|publishedResource|` (full green dot) and `|unpublishedResource|` (outlined green dot) indicate **unpublished** state: full green dot appears when a new resource is added/uploaded, and the outlined green dot appears when topics/resources titles or order are changed (cc @jtamiace and @khangmach to correct me if I'm misunderstanding). 

That's why my suggestion from #141 was to use the following aliases:

* `|unpublishedResource|` for full green dot (currently named `|publishedResource|` in this PR)
* `|unpublishedChange|` for outlined green dot (currently named `|unpublishedResource|` in this PR)

**Review by radinamatic — APPROVED** [review]
💯 🌟s for improving the contrast of that color! 🙏🏽

**Review by jtamiace — APPROVED** [review]
Sorry for the late review! :+1: for the `copyToClipboard` alias and the suggested ones for the filled/outlined dots

**Pull request merged**
