### PR TITLE
Issue 741 resolved

### LINKED ISSUE #741: KCard: Remove the border-radius on align left
🌱 **Are you new to the codebase? Welcome! Please see [the contributing guidelines](https://github.com/learningequality/kolibri-design-system/blob/develop/CONTRIBUTING.md).**

## Summary
We  need to remove  border-radius when the thumbnail display is align left using `thumbnailAlign` prop. But keep it when the the thumbnail  is align left  and   `thumbnailDisplay `prop is small
## References
This need is motivated by new additions to the cards family in Kolibri, such as

https://github.com/learningequality/kolibri/issues/12318
https://github.com/learningequality/kolibri/issues/12317
https://github.com/learningequality/kolibri/issues/12319
## Current behavior
When the card  is align left we are still seeing small rounded corners  around  the card's outer border.

 
Screenshot 2024-08-21 at 17 57 04

### Expected behavior
The border-radius  needs to be removed on `:thumbnailAlign='left`' and `:thumbnailDisplay='large'`

## Acceptance criteria

- [ ]  Implemented as specified above

### PR DESCRIPTION
**Pull request by Spoorthy1423**
#741  Removed border-radius on align left
Removed unused sections and

Removed border-radius when the thumbnail display is align left using thumbnailAlign prop and made thumbnail prop large.

#### Issue addressed

Addresses #*PR# HERE*

### Before/after screenshots
After Screenshots :
Screenshot 2024-08-24 at 6 43 33 PM

## Changelog

- [#PR no]
  - **Description:** Summary of change(s)
  - **Products impact:** Choose from - none (for internal updates) / bugfix / new API / updated API / removed API. If it's 'none', use "-" for all items below to indicate they are not relevant.
  - **Addresses:** Link(s) to GH issue(s) addressed. Include KDS links as well as links to related issues in a consumer product repository too.
  - **Components:** Affected public KDS component. Do not include internal sub-components or documentation components.
  - **Breaking:** Will this change break something in a consumer? Choose from: yes / no
  - **Impacts a11y:** Does this change improve a11y or adds new features that can be used to improve it? Choose from: yes / no
  - **Guidance:** Why and how to introduce this update to a consumer? Required for breaking changes, appreciated for changes with a11y impact, and welcomed for non-breaking changes when relevant.

[#PR no]: PR link

## Steps to test

1. Step 1
2. Step 2
3. ...

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical and brittle code paths are covered by unit tests
- [ ] The change is described in the changelog section above

## Reviewer guidance

- [ ] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?
- [ ] _Add other things to check for here_

## After review

- [ Yes ] The changelog item has been pasted to the `CHANGELOG.md`

### CODE REVIEW

**Comment by Spoorthy1423** [comment]
Hey!! @AllanOXDi i was not able to commit my changes in issue-741-resolve so had to open another pr , so sorry besides changed as per commented!! Thank you

**Comment by MisRob** [comment]
I'm sorry @Spoorthy1423, but this again has changes in package.json and yarn.lock that shouldn't be here, and were already cleared up. Let's finish in https://github.com/learningequality/kolibri-design-system/pull/754

**Comment by MisRob** [comment]
>  i was not able to commit my changes in issue-741-resolve

@Spoorthy1423 If that's because @AllanOXDi pushed into your branch to help you, you could try to delete your local branch and then checkout it out again

**Comment by MisRob** [comment]
@Spoorthy1423 By the way, it should be possible to just click "Commit suggestion" in GitHub UI. I also wanted to mention that we don't require contributors to complete the changelog, so I'm also fine doing that - feel free to let us know.

Just please respect the guidance we provided repeatedly and let's just communicate together instead of keeping opening tons of PRs, some of them having regressions in areas that were already reviewed previously. You don't need to be worried - we're glad to help with any blockers in your work in progress.

**Comment by AllanOXDi** [comment]
> if that's because @AllanOXDi pushed into your branch to help you, you could try to delete your local branch and then checkout it out again.

@Spoorthy1423 I think you need to first pull the changes from your remote before pushing .  And  after updating the suggested changes you can push with --force

**Pull request closed without merging**
