### PR TITLE
#741 Removed border-radius on align left

### PR DESCRIPTION
**Pull request by Spoorthy1423**
#741 Removed border-radius on align left
 Removed unused sections and 
 
 Removed  border-radius when the thumbnail display is align left using thumbnailAlign prop and made thumbnail prop large.

#### Issue addressed

Addresses #*PR# HERE*

## Changelog

- [#PR no]
  - **Description:** Summary of change(s)
  - **Products impact:** Choose from - none (for internal updates) / bugfix / new API / updated API / removed API. If it's 'none', use "-" for all items below to indicate they are not relevant.
  - **Addresses:** Link(s) to GH issue(s) addressed. Include KDS links as well as links to related issues in a consumer product repository too.
  - **Components:** Affected public KDS component. Do not include internal sub-components or documentation components.
  - **Breaking:** Will this change break something in a consumer? Choose from: yes / no
  - **Impacts a11y:** Does this change improve a11y or adds new features that can be used to improve it? Choose from: yes / no
  - **Guidance:** Why and how to introduce this update to a consumer? Required for breaking changes, appreciated for changes with a11y impact, and welcomed for non-breaking changes when relevant.

[#PR no]: PR link

## Steps to test

1. Step 1
2. Step 2
3. ...

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical and brittle code paths are covered by unit tests
- [ ] The change is described in the changelog section above

## Reviewer guidance

- [ ] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?
- [ ] _Add other things to check for here_

## After review

- [ ] The changelog item has been pasted to the `CHANGELOG.md`

### CODE REVIEW

**Comment by MisRob** [comment]
Hello @Spoorthy1423, you need to adjust `KCard.vue` component. Here you updated its documentation page - these changes will need to be reverted. I recommend you check out the linked contributions guidelines that contain links to dev docs that will help you to understand this repository and how to develop.

**Comment by Spoorthy1423** [comment]
Hey!! @MisRob i would love to work, on this issue further, can u please explain me the steps need to be taken

**Comment by MisRob** [comment]
Hi @Spoorthy1423. first begin with reading carefully the materials I referenced and familiarize yourself with how the library and the documentation works and what's difference between the two. Then you can find the place where thumbnail's area border radius is defined in `lib/KCard` in the given layout and update it there. I'd ask you to only submit changes that directly solve the task and also post before/after screenshots to the PR description.

**Comment by Spoorthy1423** [comment]
Hey!! @MisRob I read the material and i reverted and then did as issue asked but i think to reflect that we need to change it in border radius right??, if it is can u say me the path of border radius..

**Comment by Spoorthy1423** [comment]
@MisRob i would like to raise a pr , if any changes needed let me know

**Pull request closed without merging**
