### PR TITLE
Update $core-time value and dropshadows documentation to the latest guidance from the design team 

### PR DESCRIPTION
**Pull request by MisRob**
## Description

Based on recent guidance ([Slack thread](https://app.slack.com/client/T0KT5DC58/CTG8XDTCL)) by @jtamiace:

- Updates $core-time value from 0.25s to 0.15s
  - [Figma simulation](https://www.figma.com/proto/p7aOP2MBv0SED1uhaPwqEd/Product-rebrand?page-id=2824%3A4051&node-id=2828-6302&viewport=-174%2C174%2C0.19&t=KS4kGA1Ncw1J47h0-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2828%3A6302)
- Updates guidance for drop shadows depth to:
  - _"1dp: containers, panels, controls"_
  - _"2dp: cards, app bars, buttons, menu, tooltips, snackbars"_
  - _"6dp: card hover, modal"_
  - [Figma design](https://www.figma.com/design/p7aOP2MBv0SED1uhaPwqEd/Product-rebrand?node-id=2826-4548&t=o59cC8eg6IcLeHfA-0)

 Note that KDS consumers currently use more `dp` values. Here are issues to align products and KDS components with these guidelines at first, and then to remove unused `dp`.
- https://github.com/learningequality/kolibri-design-system/issues/724
- https://github.com/learningequality/kolibri/issues/12552
- https://github.com/learningequality/kolibri-design-system/issues/725

## Changelog

- [#723]
  - **Description:** Updates $core-time value from 0.25s to 0.15s
  - **Products impact:** User experience - faster transitions
  - **Addresses:** Updates KDS to the latest guidance from the design team
  - **Components:** `KButton`, `KExternalLink`, `KRouterLink`, `KModal`, `KCard`, `KIcon`, `KTabsList`, `KTabs`, and places in consumers that imports `$core-time`
  - **Breaking:** no
  - **Impacts a11y:** no
  - **Guidance:** -

[#723]: https://github.com/learningequality/kolibri-design-system/pull/723

- [#723]
  - **Description:** Updates drop shadows documentation to the latest guidance from the design team
  - **Products impact:** -
  - **Addresses:** Updates KDS to the latest guidance from the design team
  - **Components:** -
  - **Breaking:** no
  - **Impacts a11y:** no
  - **Guidance:** -

[#723]: https://github.com/learningequality/kolibri-design-system/pull/723

## Steps to test

- Preview "Globally available styles", "Elevation and shadow", and "Easing and timing" sections of [the Styling documentation preview page](https://deploy-preview-723--kolibri-design-system.netlify.app/styling)
- Try the live hover example in "Easing and timing" section for before/after

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included (see docs preview)
- [ ] ~Critical and brittle code paths are covered by unit tests~
- [x] The change is described in the changelog section above

## Reviewer guidance

- [ ] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?
- [ ] _Add other things to check for here_

## After review

- [x] The changelog item has been pasted to the `CHANGELOG.md

### CODE REVIEW

**Comment by MisRob** [comment]
@jtamiace I'd appreciate if you could read through the update documentation sections I linked in the "Steps to test"

**Review by jtamiace — COMMENTED** [review]
Tested and it looks great! Excited to see this refresh across the board

**Review by nucleogenesis — APPROVED** [review]
The code changes LGTM overall

**Comment by MisRob** [comment]
Thanks both

**Pull request merged**
