### PR TITLE
Issue #644 - 'Changelog' text changed to 'Release Notes'

### PR DESCRIPTION
**Pull request by musser004**
## Description

BranchLink.vue modified with 'Release Notes' instead of existing 'Changelog' text and href changed to 'https://github.com/learningequality/kolibri-design-system/releases' in order to satisfy Issue #644

#### Issue addressed

Issue #644 

### Before/after screenshots

Before:

image

After:

image

## Changelog

- [#653]
  - **Description:** Header "Changelog" text and link updated
  - **Products impact:** -
  - **Addresses:** #644 
  - **Components:** -
  - **Breaking:** -
  - **Impacts a11y:** -
  - **Guidance:** -

[#PR no]: #653

## Steps to test

1. Go to documentation home page
2. Click the "Release notes" link and confirm that it's going to the correct location

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [x] Critical and brittle code paths are covered by unit tests
- [x] The change is described in the changelog section above

## Reviewer guidance

- [ ] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?

## After review

- [ ] The changelog item has been pasted to the `CHANGELOG.md`

### CODE REVIEW

**Review by AllanOXDi — APPROVED** [review]
The changes looks good! Thanks @musser004

**Comment by AllanOXDi** [comment]
Could you update `Changelog.md `to make sure that all the checks pass

**Comment by musser004** [comment]
Hi Allen,

Thanks for reviewing. Does that changelog look correct now? First time contributing here, so I can definitely adjust that further if needed

**Comment by AllanOXDi** [comment]
Yes, everything looks good with the changelog. @musser004 . Thanks for contributing!

**Review by AlexVelezLl — APPROVED** [review]
Thanks for your contribution @musser004! :tada: LGTM!

**Pull request merged**
