### PR TITLE
Add thumb up and down icon

### PR DESCRIPTION
**Pull request by AllanOXDi**
## Description
- Add thump up icon to support search recommendation work 
#### Issue addressed

N/A
## Reviewer guidance

- [ ] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?
- [ ] _Add other things to check for here_

## After review

- [ ] The changelog item has been pasted to the `CHANGELOG.md`

### CODE REVIEW

**Comment by MisRob** [comment]
Hi @AllanOXDi, thank you. I think we'd want to target rather release-v3 branch here so it's available as part of another release soon

**Comment by AllanOXDi** [comment]
Okay! Let me do so.

**Comment by MisRob** [comment]
Thank you. Also if you could please fill in the changelog section in the PR description and then paste it to CHANGELOG.md. This will resolve the changelog check.

**Comment by AllanOXDi** [comment]
Targeting v3 branch

**Pull request closed without merging**
