### PR TITLE
Maintenance tasks 

### PR DESCRIPTION
**Pull request by MisRob**
## Description

A collection of maintenance tasks. See commit messages or changelog items below. Composables location clean up was discussed in the meeting few weeks ago.

@rtibbles Could you please check package.json updates that we talked about (browserslist, pinned dependencies)?

## Changelog

- [#558]
  - **Description:** Move `useKResponsiveWindow` from `/lib` to `/lib/composables`
  - **Products impact:** Location update
  - **Addresses:** -
  - **Components:** `useKResponsiveWindow`
  - **Breaking:** yes
  - **Impacts a11y:** -
  - **Guidance:** Update `import useKResponsiveWindow from 'kolibri-design-system/lib/useKResponsiveWindow';` from `import useKResponsiveWindow from 'kolibri-design-system/lib/composables/useKResponsiveWindow';`

[#558]: https://github.com/learningequality/kolibri-design-system/pull/558

- [#558]
  - **Description:** Remove deprecated `KResponsiveWindow's` mixin documentation page in favor of a new `useKResponsiveWindow` page
  - **Products impact:** none
  - **Addresses:** -
  - **Components:** `KResponsiveWindow`
  - **Breaking:** -
  - **Impacts a11y:** -
  - **Guidance:** -

[#558]: https://github.com/learningequality/kolibri-design-system/pull/558

- [#558]
  - **Description:** Adds engines and browserlist to package.json. Pins dependencies to exact version.
  - **Products impact:** Dependencies
  - **Addresses:** -
  - **Components:** -
  - **Breaking:** -
  - **Impacts a11y:** -
  - **Guidance:** -

[#558]: https://github.com/learningequality/kolibri-design-system/pull/558

- [#558]
  - **Description:** Internal maintenance tasks: extract common logic to utils, move private composables to `/lib/composables` and indicate that they are private by `_` prefix in their filename. dev docs updates.
  - **Products impact:** none
  - **Addresses:** -
  - **Components:** -
  - **Breaking:** -
  - **Impacts a11y:** -
  - **Guidance:** -

[#558]: https://github.com/learningequality/kolibri-design-system/pull/558

## Steps to test

- Are code changes fine?
- Preview of [useKResponsiveWindow](https://deploy-preview-558--kolibri-design-system.netlify.app/usekresponsivewindow/) page

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical and brittle code paths are covered by unit tests
- [ ] The change is described in the changelog section above

## Reviewer guidance

- [ ] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?
- [ ] _Add other things to check for here_

## After review

- [x] The changelog item has been pasted to the `CHANGELOG.md`

### CODE REVIEW

**Review by nucleogenesis — COMMENTED** [review]
Changes make sense to me thanks Misha!

**Review by akolson — APPROVED** [review]
Changes look correct to me. Thanks @MisRob

**Review by AlexVelezLl — COMMENTED** [review]
LGTM! The only question that would come to mind would be. Why does the useKDimensions have to be private? It seems to me that it could be useful in some contexts if you want to watch the windows height and width.

**Comment by MisRob** [comment]
> The only question that would come to mind would be. Why does the useKDimensions have to be private? It seems to me that it could be useful in some contexts if you want to watch the windows height and width.

**Comment by MisRob** [comment]
@AlexVelezLl 

> The only question that would come to mind would be. Why does the useKDimensions have to be private? It seems to me that it could be useful in some contexts if you want to watch the windows height and width.

In the context of this PR, it's private because it was private before, it just wasn't indicated in its name.

You're right it could be useful. If it's needed in the products, we can prepare a documentation page for it and make it public.

**Pull request merged**
