### PR TITLE
Fix dropdown menu visibility when used inside KModal

### PR DESCRIPTION
**Pull request by KshitijThareja**
## Description

This PR fixes the dropdown menu's visibility when we use KDropdownMenu in a KModal.

#### Issue addressed

Addresses #486 

### Before/after screenshots

Before:

before

After:

proof

## Changelog

  -  [#493]
  - **Description:** Changed the value of z-index of KDropdownMenu to 99.
  - **Products impact:** Bugfix
  - **Addresses:** https://github.com/learningequality/kolibri-design-system/issues/486
  - **Components:** KDropdownMenu
  - **Breaking:** No
  - **Impacts a11y:** No
  - **Guidance:**

## Steps to test

1. Add the code given in the linked issue to the file mentioned there.
2. Navigate to `KModal` documentation page to test usage of `KButton` and `KDropdownMenu`

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [x] If there are any front-end changes, before/after screenshots are included
- [ ] Critical and brittle code paths are covered by unit tests
- [x] The change is described in the changelog section above

## Reviewer guidance

- [ ] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?
- [ ] _Add other things to check for here_

## After review

- [x] The changelog item has been pasted to the `CHANGELOG.md`

### CODE REVIEW

**Comment by MisRob** [comment]
Thanks, @KshitijThareja, we will review.

**Comment by LianaHarris360** [comment]
@KshitijThareja Thanks for working on this! The code change fixes the problem and I haven't noticed any side effects within Kolibri. Before we can approve and merge this PR, the `CHANGELOG.md` file will need to be updated to include the info about this change.

**Comment by KshitijThareja** [comment]
@LianaHarris360 I've updated the CHANGELOG.md with the info about this particular change. I guess it can be merged now.
Thanks :)

**Review by LianaHarris360 — APPROVED** [review]

**Comment by MisRob** [comment]
Great @KshitijThareja, thanks!

**Pull request merged**
