### PR TITLE
Adds 'pinned' and 'unpinned' icons. Updates 'cloud' icon to outline

### PR DESCRIPTION
**Pull request by akolson**
## Description

This PR adds the `pinned` and `unpinned` icons. It also updates the `cloud` icon to an outline icons to match that in the [remote content browsing spec](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=194%3A2922).

#### Issue addressed

NA

### Before/after screenshots

NA

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical and brittle code paths are covered by unit tests
- [x] The change has been added to the `changelog`

## Reviewer guidance

- [x] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?
- [ ] _Add other things to check for here_

### CODE REVIEW

**Comment by akolson** [comment]
Hi @jtamiace  please confirm that the naming of the icons is okay. 
image

**Comment by radinamatic** [comment]
Maybe for the second would be better `not-pinned`...? 🤔

**Comment by akolson** [comment]
@radinamatic It looks like hyphens are not used in naming icons. from the convention I see only `camelCase` and `lowercase` naming. So maybe `notPinned`? Though still leaning towards maintaining the `unpinned` name :)

**Comment by radinamatic** [comment]
Thank you, I was forgetting that convention...  `notPinned` sounds good 👍🏽 

The reason I'm favoring it instead of `unpinned` is because the latter may signify that something previously has been _pinned_ and then got _unpinned_, which may not correspond to the actual user case. **`notPinned`** just declares the current state, does not give information about previous ones.

**Comment by akolson** [comment]
Thanks for this insight. Let me make this change

**Pull request merged**
