### PR TITLE
update glossary.tbx file with latest

### PR DESCRIPTION
**Pull request by indirectlylit**
## Description

Pulls latest glossary file

#### Issue addressed

fixes https://github.com/learningequality/kolibri-design-system/issues/274

### Before/after screenshots

|before | after |
|--|--|
| image | image |

## Steps to test

Compare glossary contents to crowdin

### At a high level, how did you implement this?

* ran `make i18n-download-glossary` in Kolibri repo
* manually copied to design system repo

### Does this introduce any tech-debt items?

Nothing introduced, but there's an outstanding question of how to improve this process.

## Testing checklist

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical and brittle code paths are covered by unit tests
- [ ] The change has been added to the `changelog`

## Reviewer guidance

- [ ] Is the code clean and well-commented?
- [ ] Are there tests for this change?
- [ ] Are all UI components LTR and RTL compliant (if applicable)?
- [ ] _Add other things to check for here_

## Post-merge updates and tracking

- [ ] Learning Platform update PR is submitted
- [ ] Learning Platform update PR is merged
- [ ] Studio update PR is submitted
- [ ] Studio update PR is merged
- [ ] Data Portal update PR is submitted
- [ ] Data Portal update PR is merged

### CODE REVIEW

**Comment by indirectlylit** [comment]
cc @radinamatic

**Comment by radinamatic** [comment]
We could merge this "new" glossary, but the changes in the term definitions in English are minor to minuscule, as the new terms have not been uploaded on Crowdin: all changes that you can see in the file are previous term translations in other languages, that are not visible on the KDS documentation page (hence my suggestion that **_I_** perform this update, once the new glossary has been uploaded on Crowdin 🙂).

`make i18n-download-glossary` just downloads the TBX file locally, so it would be the same as downloading it manually? Is the Crowdin glossary name hardcoded, or would it work if the glossary name is changed on Crowdin?

**Comment by indirectlylit** [comment]
Ah, didn't realize the new English glossary terms weren't even in Crowdin.

Yes, downloading manually should work fine and if necessary can just rename locally to overwrite this file.

thank you!

**Comment by radinamatic** [comment]
Sounds good, I'll open a PR as soon as the new terms are uploaded to Crowdin! 👍🏽

**Pull request closed without merging**
